export const PORTAL_THEMES = {
  luxo: {
    id: "luxo",
    name: "Luxo Clássico",
    subtitle: "Bronze, Gold & Obsidian (Escuro)",
    description: "Design sofisticado em tons de ouro e preto com alto contraste e elegância para marcas de alto padrão.",
    badge: "Ouro & Obsidian",
    isDark: true,
    previewGradient: "from-amber-950 via-stone-900 to-black",
    previewAccent: "#f59e0b",
    auth: {
      isDark: true,
      bg: "bg-stone-950 text-stone-100",
      heroBg: "bg-gradient-to-br from-amber-950/80 via-stone-900/90 to-black",
      card: "bg-stone-900/90 border-amber-900/40 text-stone-100 backdrop-blur-xl shadow-2xl shadow-amber-950/20",
      input: "bg-stone-950/90 border-amber-900/40 text-stone-100 placeholder:text-stone-500 focus:border-amber-500 focus:ring-amber-500/20",
      inputLabel: "text-stone-300 font-bold",
      primaryButton: "bg-gradient-to-r from-amber-600 via-amber-500 to-amber-600 text-stone-950 font-bold hover:from-amber-500 hover:to-amber-400 shadow-lg shadow-amber-600/20",
      secondaryButton: "bg-stone-800/90 hover:bg-stone-800 text-amber-400 border border-amber-900/40",
      backLink: "text-stone-300 hover:text-amber-400",
      bonusBanner: "bg-amber-500/10 border border-amber-500/30 text-amber-100",
      bonusTitle: "text-amber-200 font-serif font-bold text-lg",
      bonusText: "text-stone-300 text-sm",
      bonusIcon: "bg-amber-400 text-stone-950",
      textMuted: "text-stone-400",
      textHeading: "text-amber-100 font-['Playfair_Display']",
      accentText: "text-amber-400",
      tabList: "bg-black/40 border border-white/10",
      tabActive: "bg-amber-500/20 text-amber-300 border border-amber-500/40",
      tabInactive: "text-stone-400 hover:text-stone-200",
      heroBadge: "bg-amber-500/20 text-amber-400 border-amber-500/30"
    },
    dashboard: {
      isDark: true,
      bg: "bg-stone-950 text-stone-100",
      headerBg: "bg-stone-900/90 border-amber-900/40 text-stone-100 backdrop-blur-md shadow-md",
      card: "bg-stone-900/80 border-amber-900/40 text-stone-100 backdrop-blur-md shadow-xl shadow-amber-950/10",
      cardHeader: "border-amber-900/40",
      modalCard: "bg-stone-900 border-amber-900/50 text-stone-100 shadow-2xl",
      statCard: "bg-stone-900/80 border-amber-900/40 text-stone-100 shadow-xl hover:border-amber-500/40 transition-colors",
      statLabel: "text-amber-400/90 font-bold uppercase tracking-wider text-[10px]",
      statValue: "text-stone-100 font-black text-xl",
      statIcon: "w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-center justify-center",
      statusCard: "bg-stone-900/90 border-amber-900/40 text-stone-100 shadow-lg",
      statusBadge: "bg-stone-950/80 border-amber-900/40",
      statusMemberText: "text-amber-300 font-bold text-sm",
      heroTitle: "text-stone-100 font-black",
      heroName: "bg-gradient-to-r from-amber-400 via-amber-300 to-amber-200 text-transparent bg-clip-text font-black",
      heroSubtitle: "text-stone-300 font-medium",
      alertBanner: "bg-gradient-to-r from-amber-950/90 via-stone-900/95 to-amber-950/90 border-amber-500/50 text-stone-100 shadow-xl",
      alertTitle: "text-amber-200 font-bold text-sm",
      alertText: "text-stone-300 text-xs",
      alertButton: "bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-stone-950 font-bold shadow-md shadow-amber-500/20",
      primaryAccent: "from-amber-600 to-amber-500 text-stone-950",
      primaryButton: "bg-gradient-to-r from-amber-600 via-amber-500 to-amber-600 text-stone-950 font-bold hover:from-amber-500 hover:to-amber-400 shadow-lg shadow-amber-600/20",
      secondaryButton: "bg-stone-800/90 hover:bg-stone-800 text-amber-400 border border-amber-900/40",
      logoutBtn: "bg-stone-900 hover:bg-stone-800 text-stone-200 border border-stone-800 hover:border-amber-900/40",
      input: "bg-stone-950/90 border-amber-900/40 text-stone-100 placeholder:text-stone-500 focus:border-amber-500 focus:ring-amber-500/20",
      inputReadOnly: "bg-stone-950/60 border-stone-800 text-stone-400",
      inputLabel: "text-amber-400/90 font-bold uppercase tracking-widest text-[10px] bg-stone-900",
      accentText: "text-amber-400 font-semibold",
      textHeading: "font-['Playfair_Display'] text-stone-100 font-bold",
      textMuted: "text-stone-400",
      tableHeader: "text-amber-400/90 border-amber-900/40 font-bold text-[10px] uppercase tracking-widest",
      tableRowHover: "hover:bg-amber-950/40",
      tableRowBorder: "border-amber-900/20",
      tableText: "text-stone-200",
      tableHighlight: "text-amber-100 font-bold",
      badge: "bg-amber-500/20 text-amber-400 border border-amber-500/30",
      loyaltyBg: "bg-gradient-to-br from-stone-900 via-amber-950/60 to-black text-white border-amber-900/50 shadow-2xl",
      rewardUnlocked: "bg-gradient-to-r from-amber-500/15 to-stone-900 border-amber-500/40 text-amber-100 shadow-md",
      rewardLocked: "bg-stone-950/60 border-stone-800 text-stone-400 opacity-60",
      profileAvatarBox: "bg-stone-950 p-2 shadow-inner border border-amber-900/40",
      profileAvatarInner: "bg-gradient-to-br from-amber-950 to-stone-900 text-amber-400 font-black text-3xl border border-amber-500/30",
      profileFieldBox: "bg-stone-950/80 border border-amber-900/40 text-stone-200",
      profileFieldLabel: "text-amber-400/90 font-bold uppercase tracking-widest text-[10px]"
    }
  },
  minimalista: {
    id: "minimalista",
    name: "Minimalista Clean",
    subtitle: "Nordic White & Emerald (Claro - Alto Contraste)",
    description: "Interface clara, moderna e objetiva, com tipografia escura de altíssima legibilidade e detalhes esmeralda.",
    badge: "Nordic Clean",
    isDark: false,
    previewGradient: "from-slate-50 via-white to-emerald-50",
    previewAccent: "#059669",
    auth: {
      isDark: false,
      bg: "bg-slate-50 text-slate-900",
      heroBg: "bg-gradient-to-br from-slate-900/95 via-emerald-950/90 to-slate-900",
      card: "bg-white border-slate-200 text-slate-900 shadow-2xl shadow-slate-200/50",
      input: "bg-slate-50 border-slate-300 text-slate-900 placeholder:text-slate-400 focus:border-emerald-600 focus:ring-emerald-600/20",
      inputLabel: "text-slate-700 font-bold",
      primaryButton: "bg-emerald-600 hover:bg-emerald-700 text-white font-bold shadow-md shadow-emerald-600/20",
      secondaryButton: "bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-300",
      backLink: "text-slate-700 hover:text-slate-950 font-semibold",
      bonusBanner: "bg-emerald-50 border border-emerald-300 text-emerald-950 shadow-sm",
      bonusTitle: "text-emerald-950 font-serif font-bold text-lg",
      bonusText: "text-emerald-800 text-sm font-medium",
      bonusIcon: "bg-emerald-600 text-white",
      textMuted: "text-slate-500",
      textHeading: "text-slate-900 font-sans tracking-tight font-bold",
      accentText: "text-emerald-600 font-bold",
      tabList: "bg-slate-100 border border-slate-200",
      tabActive: "bg-white text-emerald-700 border border-emerald-200 shadow-sm font-bold",
      tabInactive: "text-slate-600 hover:text-slate-900",
      heroBadge: "bg-emerald-500/20 text-emerald-300 border-emerald-400/30"
    },
    dashboard: {
      isDark: false,
      bg: "bg-slate-50 text-slate-900",
      headerBg: "bg-white/95 border-slate-200 text-slate-900 backdrop-blur-md shadow-sm",
      card: "bg-white border-slate-200 text-slate-900 shadow-sm hover:shadow-md transition-shadow",
      cardHeader: "border-slate-100",
      modalCard: "bg-white border-slate-200 text-slate-900 shadow-2xl",
      statCard: "bg-white border-slate-200 text-slate-900 shadow-sm hover:border-emerald-500/50 hover:shadow-md transition-all",
      statLabel: "text-slate-500 font-bold uppercase tracking-wider text-[10px]",
      statValue: "text-slate-900 font-black text-xl",
      statIcon: "w-12 h-12 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-700 flex items-center justify-center",
      statusCard: "bg-white border-slate-200 text-slate-900 shadow-sm",
      statusBadge: "bg-slate-50 border-slate-200",
      statusMemberText: "text-emerald-700 font-bold text-sm",
      heroTitle: "text-slate-900 font-black",
      heroName: "text-emerald-700 font-black",
      heroSubtitle: "text-slate-600 font-medium",
      alertBanner: "bg-emerald-50/90 border-emerald-300 text-emerald-950 shadow-md",
      alertTitle: "text-emerald-950 font-bold text-sm",
      alertText: "text-emerald-800 text-xs font-medium",
      alertButton: "bg-emerald-600 hover:bg-emerald-700 text-white font-bold shadow-md shadow-emerald-600/20",
      primaryAccent: "from-emerald-600 to-teal-600 text-white",
      primaryButton: "bg-emerald-600 hover:bg-emerald-700 text-white font-bold shadow-md shadow-emerald-600/20",
      secondaryButton: "bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-300",
      logoutBtn: "bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200",
      input: "bg-slate-50 border-slate-300 text-slate-900 placeholder:text-slate-400 focus:border-emerald-600 focus:ring-emerald-600/20",
      inputReadOnly: "bg-slate-100 border-slate-200 text-slate-500",
      inputLabel: "text-slate-700 font-bold uppercase tracking-widest text-[10px] bg-white",
      accentText: "text-emerald-600 font-bold",
      textHeading: "font-sans font-bold text-slate-900",
      textMuted: "text-slate-500",
      tableHeader: "text-slate-600 border-slate-200 font-bold text-[10px] uppercase tracking-widest",
      tableRowHover: "hover:bg-slate-50",
      tableRowBorder: "border-slate-100",
      tableText: "text-slate-700",
      tableHighlight: "text-slate-900 font-bold",
      badge: "bg-emerald-50 text-emerald-700 border border-emerald-200 font-bold",
      loyaltyBg: "bg-gradient-to-br from-slate-900 via-emerald-950 to-slate-950 text-white border-emerald-800/40 shadow-xl",
      rewardUnlocked: "bg-emerald-50/80 border-emerald-200 text-emerald-950 shadow-sm",
      rewardLocked: "bg-slate-50 border-slate-200 text-slate-500 opacity-60",
      profileAvatarBox: "bg-slate-100 p-2 shadow-inner border border-slate-200",
      profileAvatarInner: "bg-gradient-to-br from-emerald-600 to-teal-700 text-white font-black text-3xl shadow-sm",
      profileFieldBox: "bg-slate-50 border border-slate-200 text-slate-800",
      profileFieldLabel: "text-slate-500 font-bold uppercase tracking-widest text-[10px]"
    }
  },
  vibrante: {
    id: "vibrante",
    name: "Moderno Vibrante",
    subtitle: "Cyber Indigo & Violeta (Gradiente Tech)",
    description: "Estilo tech moderno com cores vivas, transparências e brilhos dinâmicos.",
    badge: "Cyber Violet",
    isDark: true,
    previewGradient: "from-slate-900 via-indigo-950 to-violet-950",
    previewAccent: "#6366f1",
    auth: {
      isDark: true,
      bg: "bg-slate-950 text-slate-100",
      heroBg: "bg-gradient-to-br from-indigo-950/90 via-violet-900/80 to-slate-950",
      card: "bg-slate-900/80 border-indigo-500/30 text-slate-100 backdrop-blur-2xl shadow-2xl shadow-indigo-950/40",
      input: "bg-slate-950/60 border-indigo-500/30 text-slate-100 placeholder:text-slate-500 focus:border-indigo-400 focus:ring-indigo-400/20",
      inputLabel: "text-slate-300 font-bold",
      primaryButton: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white font-bold hover:opacity-90 shadow-lg shadow-indigo-500/25",
      secondaryButton: "bg-slate-800/80 hover:bg-slate-800 text-indigo-300 border border-indigo-500/30",
      backLink: "text-slate-300 hover:text-indigo-400",
      bonusBanner: "bg-indigo-500/10 border border-indigo-500/30 text-indigo-100",
      bonusTitle: "text-indigo-200 font-serif font-bold text-lg",
      bonusText: "text-slate-300 text-sm",
      bonusIcon: "bg-indigo-500 text-white",
      textMuted: "text-slate-400",
      textHeading: "text-transparent bg-clip-text bg-gradient-to-r from-indigo-200 via-purple-200 to-pink-200 font-bold",
      accentText: "text-indigo-400",
      tabList: "bg-black/40 border border-white/10",
      tabActive: "bg-indigo-500/20 text-indigo-300 border border-indigo-500/40",
      tabInactive: "text-slate-400 hover:text-slate-200",
      heroBadge: "bg-indigo-500/20 text-indigo-300 border-indigo-400/30"
    },
    dashboard: {
      isDark: true,
      bg: "bg-slate-950 text-slate-100",
      headerBg: "bg-slate-900/90 border-indigo-900/40 text-slate-100 backdrop-blur-md shadow-md",
      card: "bg-slate-900/80 border-indigo-500/30 text-slate-100 backdrop-blur-md shadow-xl shadow-indigo-950/30",
      cardHeader: "border-indigo-900/40",
      modalCard: "bg-slate-900 border-indigo-500/40 text-slate-100 shadow-2xl",
      statCard: "bg-slate-900/80 border-indigo-500/30 text-slate-100 shadow-xl hover:border-indigo-400/50 transition-colors",
      statLabel: "text-indigo-300 font-bold uppercase tracking-wider text-[10px]",
      statValue: "text-slate-100 font-black text-xl",
      statIcon: "w-12 h-12 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 flex items-center justify-center",
      statusCard: "bg-slate-900/90 border-indigo-900/40 text-slate-100 shadow-lg",
      statusBadge: "bg-slate-950/80 border-indigo-900/40",
      statusMemberText: "text-indigo-300 font-bold text-sm",
      heroTitle: "text-slate-100 font-black",
      heroName: "bg-gradient-to-r from-indigo-300 via-purple-300 to-pink-300 text-transparent bg-clip-text font-black",
      heroSubtitle: "text-slate-300 font-medium",
      alertBanner: "bg-gradient-to-r from-indigo-950/90 via-slate-900/95 to-purple-950/90 border-indigo-500/50 text-slate-100 shadow-xl",
      alertTitle: "text-indigo-200 font-bold text-sm",
      alertText: "text-slate-300 text-xs",
      alertButton: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white font-bold hover:opacity-90 shadow-md shadow-indigo-500/25",
      primaryAccent: "from-indigo-500 via-purple-500 to-pink-500 text-white",
      primaryButton: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white font-bold hover:opacity-95 shadow-lg shadow-indigo-500/25",
      secondaryButton: "bg-slate-800/90 hover:bg-slate-800 text-indigo-300 border border-indigo-500/40",
      logoutBtn: "bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-800 hover:border-indigo-900/40",
      input: "bg-slate-950/90 border-indigo-500/40 text-slate-100 placeholder:text-slate-500 focus:border-indigo-400 focus:ring-indigo-400/20",
      inputReadOnly: "bg-slate-950/60 border-slate-800 text-slate-400",
      inputLabel: "text-indigo-300 font-bold uppercase tracking-widest text-[10px] bg-slate-900",
      accentText: "text-indigo-400 font-semibold",
      textHeading: "font-sans font-bold text-slate-100",
      textMuted: "text-slate-400",
      tableHeader: "text-indigo-300/90 border-indigo-900/40 font-bold text-[10px] uppercase tracking-widest",
      tableRowHover: "hover:bg-indigo-950/40",
      tableRowBorder: "border-indigo-900/30",
      tableText: "text-slate-200",
      tableHighlight: "text-slate-100 font-bold",
      badge: "bg-indigo-500/20 text-indigo-300 border border-indigo-500/40",
      loyaltyBg: "bg-gradient-to-br from-indigo-950 via-purple-950 to-slate-950 text-white border-indigo-500/40 shadow-2xl",
      rewardUnlocked: "bg-gradient-to-r from-indigo-500/20 to-purple-900/30 border-indigo-500/40 text-indigo-100 shadow-md",
      rewardLocked: "bg-slate-950/60 border-slate-800 text-slate-400 opacity-60",
      profileAvatarBox: "bg-slate-950 p-2 shadow-inner border border-indigo-900/40",
      profileAvatarInner: "bg-gradient-to-br from-indigo-900 to-purple-950 text-indigo-300 font-black text-3xl border border-indigo-500/30",
      profileFieldBox: "bg-slate-950/80 border border-indigo-500/30 text-slate-200",
      profileFieldLabel: "text-indigo-300 font-bold uppercase tracking-widest text-[10px]"
    }
  },
  terracota: {
    id: "terracota",
    name: "Executivo Warm",
    subtitle: "Terracota & Madeira Nobre (Claro - Alto Contraste)",
    description: "Tons terrosos nobres com fundo quente claro, tipografia escura nítida e detalhes terracota de alto contraste.",
    badge: "Warm Earth",
    isDark: false,
    previewGradient: "from-stone-100 via-amber-50 to-orange-100",
    previewAccent: "#c2410c",
    auth: {
      isDark: false,
      bg: "bg-[#fbf9f5] text-stone-900",
      heroBg: "bg-gradient-to-br from-stone-950/95 via-orange-950/90 to-amber-950",
      card: "bg-white border-stone-200 text-stone-900 shadow-2xl shadow-orange-950/5",
      input: "bg-stone-50 border-stone-300 text-stone-900 placeholder:text-stone-400 focus:border-orange-600 focus:ring-orange-600/20",
      inputLabel: "text-stone-700 font-bold",
      primaryButton: "bg-gradient-to-r from-orange-700 to-amber-700 hover:from-orange-800 hover:to-amber-800 text-white font-bold shadow-md shadow-orange-700/20",
      secondaryButton: "bg-amber-100/70 hover:bg-amber-100 text-orange-900 border border-orange-900/10",
      backLink: "text-stone-700 hover:text-orange-900 font-semibold",
      bonusBanner: "bg-orange-50 border border-orange-200 text-orange-950 shadow-sm",
      bonusTitle: "text-orange-950 font-serif font-bold text-lg",
      bonusText: "text-orange-900/90 text-sm font-medium",
      bonusIcon: "bg-orange-600 text-white",
      textMuted: "text-stone-500",
      textHeading: "text-stone-900 font-['Playfair_Display'] font-bold",
      accentText: "text-orange-700 font-bold",
      tabList: "bg-stone-100 border border-stone-200",
      tabActive: "bg-white text-orange-800 border border-orange-200 shadow-sm font-bold",
      tabInactive: "text-stone-600 hover:text-stone-900",
      heroBadge: "bg-orange-500/20 text-orange-300 border-orange-400/30"
    },
    dashboard: {
      isDark: false,
      bg: "bg-[#fbf9f5] text-stone-900",
      headerBg: "bg-white/95 border-stone-200 text-stone-900 backdrop-blur-md shadow-sm",
      card: "bg-white border-stone-200 text-stone-900 shadow-sm hover:shadow-md transition-shadow",
      cardHeader: "border-stone-100",
      modalCard: "bg-white border-stone-200 text-stone-900 shadow-2xl",
      statCard: "bg-white border-stone-200 text-stone-900 shadow-sm hover:border-orange-500/50 hover:shadow-md transition-all",
      statLabel: "text-stone-500 font-bold uppercase tracking-wider text-[10px]",
      statValue: "text-stone-900 font-black text-xl",
      statIcon: "w-12 h-12 rounded-2xl bg-orange-50 border border-orange-200 text-orange-700 flex items-center justify-center",
      statusCard: "bg-white border-stone-200 text-stone-900 shadow-sm",
      statusBadge: "bg-stone-50 border-stone-200",
      statusMemberText: "text-orange-800 font-bold text-sm",
      heroTitle: "text-stone-900 font-black",
      heroName: "bg-gradient-to-r from-orange-700 via-amber-800 to-amber-700 text-transparent bg-clip-text font-black",
      heroSubtitle: "text-stone-600 font-medium",
      alertBanner: "bg-orange-50/90 border-orange-200 text-orange-950 shadow-md",
      alertTitle: "text-orange-950 font-bold text-sm",
      alertText: "text-orange-900/90 text-xs font-medium",
      alertButton: "bg-gradient-to-r from-orange-700 to-amber-700 hover:from-orange-800 hover:to-amber-800 text-white font-bold shadow-md shadow-orange-700/20",
      primaryAccent: "from-orange-700 to-amber-800 text-white",
      primaryButton: "bg-gradient-to-r from-orange-700 to-amber-700 hover:from-orange-800 hover:to-amber-800 text-white font-bold shadow-md shadow-orange-700/20",
      secondaryButton: "bg-amber-100/70 hover:bg-amber-100 text-orange-900 border border-orange-900/10",
      logoutBtn: "bg-stone-100 hover:bg-stone-200 text-stone-700 border border-stone-200",
      input: "bg-stone-50 border-stone-300 text-stone-900 placeholder:text-stone-400 focus:border-orange-600 focus:ring-orange-600/20",
      inputReadOnly: "bg-stone-100 border-stone-200 text-stone-500",
      inputLabel: "text-stone-700 font-bold uppercase tracking-widest text-[10px] bg-white",
      accentText: "text-orange-700 font-bold",
      textHeading: "font-['Playfair_Display'] text-stone-900 font-bold",
      textMuted: "text-stone-500",
      tableHeader: "text-stone-600 border-stone-200 font-bold text-[10px] uppercase tracking-widest",
      tableRowHover: "hover:bg-amber-50/60",
      tableRowBorder: "border-stone-100",
      tableText: "text-stone-700",
      tableHighlight: "text-stone-900 font-bold",
      badge: "bg-orange-50 text-orange-800 border border-orange-200 font-bold",
      loyaltyBg: "bg-gradient-to-br from-stone-900 via-orange-950 to-stone-950 text-white border-orange-900/40 shadow-xl",
      rewardUnlocked: "bg-orange-50/90 border-orange-200 text-stone-900 shadow-sm",
      rewardLocked: "bg-stone-50 border-stone-200 text-stone-500 opacity-60",
      profileAvatarBox: "bg-stone-100 p-2 shadow-inner border border-stone-200",
      profileAvatarInner: "bg-gradient-to-br from-orange-700 to-amber-800 text-white font-black text-3xl shadow-sm",
      profileFieldBox: "bg-stone-50 border border-stone-200 text-stone-800",
      profileFieldLabel: "text-stone-500 font-bold uppercase tracking-widest text-[10px]"
    }
  }
};

export const DEFAULT_PORTAL_THEME = "luxo";

export function getPortalTheme(themeId) {
  return PORTAL_THEMES[themeId] || PORTAL_THEMES[DEFAULT_PORTAL_THEME];
}
