FROM node:18-slim

# 1. Instalar dependências básicas para o Chromium no Linux
RUN apt-get update && apt-get install -y \
  wget \
  gnupg \
  curl \
  psmisc \
  ca-certificates \
  fonts-liberation \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgbm1 \
  libgcc1 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  lsb-release \
  xdg-utils \
  && rm -rf /var/lib/apt/lists/*

# 2. Configurar diretório de trabalho
WORKDIR /usr/src/app

# 3. Copiar arquivos do projeto
COPY package*.json ./
RUN npm install

COPY . .

# 4. Variáveis de Ambiente para o Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false

# 5. Expor a porta
EXPOSE 3001

# 6. Rodar o robô
CMD [ "node", "server.js" ]